src/main/java/javax/servlet/ServletContext.java
src/main/java/javax/servlet/ServletRequest.java

Fixes #129 
I didn't use the exact text suggested. I tried to make it both shorter and more explicit about the potential consequences of not using these parts of the API with care.

Add security text to Javadoc to fix #129

---

src/main/java/javax/servlet/ServletContext.java

There was a conflict between the large reformat fix and the Javadoc updates. This text wasn't in conflict so the format wasn't updated.

Format part of fix for #126 that wasn't reformatted on merge

---

pom.xml
src/main/java/javax/servlet/Servlet.java
src/main/java/javax/servlet/ServletRequest.java
src/main/javadoc/javax.servlet-api.css

Therefore the license header needs to be updated. All of them became
longer than 80 chars. I opted to break the line in the same place as it
will make any future automated license header checking simpler to
implement (based on my experience of this in the WebSocket project).

All of these files have been modified since the initial contribution.

---

api/src/main/java/javax/servlet/ServletRequest.java

Addresses Jakarta EE 8 TCK signature test failure with master/4.0.4 branches: 
> javax.servlet.ServletRequest: getRealPath(java.lang.String):anno 0 java.lang.Deprecated())
Signed-off-by: Scott Marlow <smarlow@redhat.com>

remove Deprecated tag as workaround for TCK signature failure 

---

api/src/main/java/javax/servlet/http/Part.java

Fix for #274
The javadoc for Part.write(String) contained the contradictory sentence: "Absolute paths are used as provided and are relative to <code>getLocation()</code>."
Changed to the agreed text: "Relative paths are relative to MultipartConfigElement.getLocation(). Absolute paths are used as provided."

[274] Corrected javadoc for Part.write(String)

---

spec/pom.xml

This PR addresses two issues that were identified by building on a larger ranger of JDKs, particularly newer ones.
On the CI system (although I can't replicate it locally) some very new JDKs report java.lang.ExceptionInInitializerError. Updating latest version fixes this (at least it did for WebSocket).
The spec module added a requirement for Java 8 or lower. This doesn't seem right and prevents building on newer JDKs. Fix this by changing JDK range (to align with the range used by WebSocket).

Enable building on newer JDKs

---

api/src/main/java/jakarta/servlet/http/HttpServletRequest.java

For issue [2] of  #309
Reword the javadoc to align `getHttpServletMapping` under async dispatch to be similar to a `Dispatcher.forward(...)`.  The wording in this section is a bit cumbersome, but I've tried to add clarity without changing it too much.
Signed-off-by: Greg Wilkins <gregw@webtide.com>

Async Dispatch HttpServletMapping

---

api/src/main/java/jakarta/servlet/ServletRequest.java
api/src/main/java/jakarta/servlet/http/HttpServletRequest.java

I ended up needing to fix a bit more for #368:
+ reference to RFC 7239  for obtaining local/remote IP and ports
+ removed historic references to CGI variables
+ relaxed the dependence on the host header, which may not be present in HTTP/2
+ removed the reference to dotted IP address form (no longer valid for IPv6)
I'm wondering if we should also say anything about [] around IPv6?

Fixes #368 Updates javadoc for getRemoteAddr

---

spec/src/main/asciidoc/servlet-spec-body.adoc

Fixes #363
This should address most of comments in the issue, bar a few things:
> In Chapt. 14, Deployment Descriptors the text still says "All legacy deployment descriptors must be supported." I am not sure if that will be possible. Please review and update the text if needed.
Not sure what to do about this one. The XML does not directly reference package names so really there is no reason why we can't support old versions, but old apps will be using the old namespace which clearly won't work without some form of transformation. Maybe we should just drop this requirement from the spec altogether, and leave it up to the implementations as to what they support (however add it back in 5.1, so 5.1 needs to support 5.0 descriptors).
> References to external specifications probably need to …

Some more spec document cleanup

---

spec/src/main/asciidoc/servlet-spec-body.adoc

Fix #365 - correct fragment order in example 2

---

api/src/main/java/jakarta/servlet/ServletResponse.java

There are two things to check here. First that the clarified behaviour is as required. There were a few edge cases where I had to make some judgement calls. Once we are happy with the defined behaviour we can polish the wording.

Fix #377 - clarify setCharacterEncoding(null) and related

---

api/pom.xml

The previous version of the plug-in triggers a
ConcurrentModificationException on newer JREs. The likely root cause is
https://hg.openjdk.java.net/jdk/jdk/rev/65b345254ca3
The newer maven-bundle-plugin has been updated to avoid the issue.

Update maven-bundle-plugin to latest to fix CI failure with newer JREs

---

api/src/main/java/jakarta/servlet/ServletContext.java

The version info in the Javadoc wasn't updated for 5.0

Fixes # 383 Fix Javadoc for getMajorVersion and getMinorVersion

---

api/src/main/java/jakarta/servlet/ServletConnection.java
api/src/main/java/jakarta/servlet/ServletRequest.java
api/src/main/java/jakarta/servlet/ServletRequestWrapper.java

This is a first pass. I think it is sufficient for 6.0 but I'm expecting suggestions for improvements.
An earlier draft tried to combine container generated IDs for protocols that didn't define them and protocol defined IDs for protocols that did. That didn't work too well primarily because the h2 stream ID is not unique. Working around that quickly got messy and separating out container generated IDs and protocol IDs was the neatest solution I can find.
I'd have no objection to including remote/local address and port at this stage and maybe some additional TLS details as well.
Thoughts?

Fix #407 add identifiers for debug logging

---

spec/pom.xml

Some required config changes due to breaking changes in v2.
See https://docs.asciidoctor.org/maven-tools/latest/plugin/v2-migration-guide/

Update maven spec dependencies, specifically of asciidoc

---

api/src/main/java/jakarta/servlet/ServletContext.java
spec/src/main/asciidoc/servlet-spec-body.adoc

Remove the restriction on programatically added listeners calling getter
methods on the ServletContext.
Fixes #416

Remove restriction on ServletContext getters

---

api/pom.xml
api/src/main/java/module-info.java
api/src/test/java/jakarta/servlet/http/CookieTest.java
spec/src/main/asciidoc/servlet-spec-body.adoc

Fixes #201
Module name is `jakarta.servlet` (Per the naming [conventions](https://github.com/jakartaee/specification-committee/blob/master/names.adoc))
Exports the 4 API packages
Opens the 4 API packages as well to prevent errors like:
```
[ERROR] jakarta.servlet.http.CookieTest.testValue  Time elapsed: 0 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: 
Unable to make jakarta.servlet.http.CookieTest() accessible: 
module jakarta.servlet does not "opens jakarta.servlet.http" to unnamed module @ffaa6af
```

Add a module-info.java

---

api/src/main/java/jakarta/servlet/SessionCookieConfig.java
api/src/main/java/jakarta/servlet/http/Cookie.java
api/src/test/java/jakarta/servlet/http/CookieTest.java
spec/src/main/asciidoc/servlet-spec-body.adoc

In summary:
- setVersion() is NO-OP, getVersion() is hard-coded to 0
- Restrictions on cookie name relaxed to 'must be non-null, non-empty token'
The reason I am proposing this for 6.0 as that I started to look at the TCK and noted that Tomcat's "pass the TCK" mode included various settings for use RFC 2109 rather than RFC 6265. I also recall a TCK challenge caused by the Javadoc continuing to refer to RFC 2109. It struck me that we really should try and get this into 6.0.
The changes turned out to be fairly minimal. Effectively disabling version should have minimal effect as RFC 2965 was never really implemented by any browser.
Reducing the restrictions on cookie names should safe as well.

Fix #37 - update Cookie class for RFC 6265

---

api/src/main/java/jakarta/servlet/ServletOutputStream.java

The current wording is causing confusion:
https://bz.apache.org/bugzilla/show_bug.cgi?id=65780

Align isReady in ServletOutputStream with ServletInputStream

---

api/pom.xml
spec/src/main/asciidoc/servlet-spec-body.adoc

Checking everything after the schema update I noticed there was a Javadoc change in 2022 but the Javadoc was copyrighted 2021. I've fixed that.
That got me looking at the spec document where I noticed the Javadoc change wasn't listed in the changelog so I fixed that too. That triggered a copyright date change for the spec doc - which has the benefit of aligning the copyright dates for the spec doc and the Java doc,

Copyright updates

---

api/src/main/java/jakarta/servlet/http/HttpServletRequest.java
spec/src/main/asciidoc/servlet-spec-body.adoc

Fixes #325 
This one is not clear-cut. There are a couple of different options for how we could handle this.
This PR implements the more backwards compatible approach which is to align with  `getHeader()` and state that if there are multiple headers with the same name, only the first is used.
Alternatives include:
- throw an exception if there is more than one header with the given name
- throw an exception if there is more than one header with the given name and the values are not identical (return the value if they are identical).
- something else
Given the potential for breakage if an exception is thrown, I think alignment with `getHeader()` is the way to go.

Fix issue #325 - Clarify get[Int|Date]Header() for multiple headers

---

api/src/main/java/jakarta/servlet/http/HttpServletRequest.java

Align Javadoc with current behaviour.
The default current behaviour is consistent with an implementation that does not implement trailer fields. isTrailerFieldsReady() returns true and a subsequent call to getTrailerFields() returns an empty Map.

Fix Javadoc issue highlighted by #473

---

api/pom.xml
pom.xml
spec/pom.xml
spec/src/main/asciidoc/servlet-spec-body.adoc

This assumes we won't be making any breaking changes / significant new features in the next release. If there are plans for that, we'll need to move to 7.0

Update version to 6.1

---

api/src/main/java/jakarta/servlet/http/HttpServletResponse.java
spec/src/main/asciidoc/servlet-spec-body.adoc

Doesn't mandate any new behaviour, just opens the door for containers that want to to use relative redirects while remaining specification compliant.

Fix #275 - containers can use relative URLS for redirects

---

api/src/main/java/jakarta/servlet/ServletInputStream.java
api/src/main/java/jakarta/servlet/ServletOutputStream.java
spec/src/main/asciidoc/servlet-spec-body.adoc

Could be applied as-is but more likely to be a starting point for discussion.
The default implementations could be more efficient but I opted for clarity over efficiency given that containers should be overriding these methods anyway.
One obvious question - to we want to add scatter/gather read/write?

Fix issue-484 Add read/write via ByteBuffer

---

api/src/main/java/jakarta/servlet/ServletContext.java
api/src/main/java/jakarta/servlet/http/HttpServletRequest.java
spec/src/main/asciidoc/servlet-spec-body.adoc

This is intended to fix #453
The first commit should be uncontroversial.
I suspect the second commit will require some discussion but, logically, I don't currently see any viable alternative. My reasoning for this is explained in https://github.com/jakartaee/servlet/issues/453#issuecomment-982404860

Fix issue 453

---

api/src/main/java/jakarta/servlet/http/HttpServletMapping.java
spec/src/main/asciidoc/servlet-spec-body.adoc

This PR fixes #316 and #300.
I think the changes are fairly non-controversial but we may want to discuss the clarification for the mapping of servlets using context root mapping.

Fix mapping issues

---

api/src/main/java/jakarta/servlet/AsyncContext.java
api/src/main/java/jakarta/servlet/ReadListener.java
api/src/main/java/jakarta/servlet/ServletOutputStream.java
api/src/main/java/jakarta/servlet/WriteListener.java
spec/src/main/asciidoc/servlet-spec-body.adoc

This turned out to be a much smaller change than I was expecting - primarily because applications still need to call `complete()` or `dispatch()` after they call `ServletOutputSream.close()`.

Fix #273 - clarify behaviour around non-blocking writes

---

api/src/main/java/jakarta/servlet/ServletRequest.java
spec/src/main/asciidoc/servlet-spec-body.adoc

Applies to all of the parameter methods.
Containers may provide options for alternative error handling.
I am leaving this in draft for others to provide feedback while I work on implementing this in Tomcat to check I haven't missed anything.

Fix #431 - getParameter() may throw runtime exception

---

tck/README.md
tck/tck-runtime/src/main/java/servlet/tck/api/jakarta_servlet/dispatchtest/DispatchTestServlet.java
tck/tck-runtime/src/main/java/servlet/tck/api/jakarta_servlet/dispatchtest/DispatchTests.java
tck/tck-runtime/src/main/java/servlet/tck/api/jakarta_servlet/dispatchtest/DispatchTests11.java
tck/tck-runtime/src/main/java/servlet/tck/api/jakarta_servlet/dispatchtest/DispatchTests12.java
tck/tck-runtime/src/main/java/servlet/tck/api/jakarta_servlet_http/httpsessionx/ExpireHttpSession.java
tck/tck-runtime/src/main/java/servlet/tck/api/jakarta_servlet_http/httpsessionx/TestServlet.java
tck/tck-runtime/src/main/java/servlet/tck/common/util/ServletTestUtil.java

The idea is to keep the tests for containers supporting it.
But if not containers must set the system property `servlet.tck.support.crossContext` to `false`

Do not fail when tests when cross context not supported (as it is not mandatory per spec)

---

api/src/main/java/jakarta/servlet/http/HttpSessionIdListener.java

The fix should not be controversial. I intend to merge this pretty much immediately.

Fix #569 - correct sessionIdChanged() Javadoc

---

tck/pom.xml

If I am reading the CI errors correctly, the use of Servlet parent is preventing the TCK module from completing an independent release. We need to release the API and the TCK separately.

Remove Servlet parent

---

api/src/main/java/jakarta/servlet/http/Cookie.java

This should be uncontroversial. The removed text is the exact opposite of RFC 6265.

Remove incorrect comment

---

tck/tck-runtime/src/main/java/servlet/tck/api/jakarta_servlet/servletcontext/TestServlet.java

This should be uncontroversial. It simply updates the expected minor version from `0` to `1`. Therefore I intend to merge this immediately.

Fix minor version test - update expected to "1" for version 6.1

---

api/pom.xml

Issue #578 make produced META-INF/MANIFEST.MF reproducible

---

tck/README.md
tck/tck-runtime/src/main/java/servlet/tck/spec/serverpush/ServerPushTests.java

Creates a system property that can be set to skip the tests that require h2 push to be working.
I'm intending to allow at least 24 hours for review of this PR.

Add ability to skip the HTTP/2 Push tests

---

tck/tck-runtime/src/main/java/servlet/tck/api/jakarta_servlet_http/httpservletrequest/HttpServletRequestTests.java

Ignore content-length and vary headers
This should be fairly uncontroversial but it is a change so I am intending to allow at least 24 hours, and hopefully longer, for review.

Align HEAD TCK test with RFC 9110, section 9.3.2

---

.github/workflows/maven.yml
tck/tck-runtime/pom.xml
tck/tck-runtime/src/main/java/servlet/tck/signature/PackageList.java
tck/tck-runtime/src/main/java/servlet/tck/signature/ServletSigTest.java
tck/tck-runtime/src/main/java/servlet/tck/signature/SigTest.java
tck/tck-runtime/src/main/java/servlet/tck/signature/SigTestData.java
tck/tck-runtime/src/main/java/servlet/tck/signature/SigTestDriver.java
tck/tck-runtime/src/main/java/servlet/tck/signature/SigTestResult.java
tck/tck-runtime/src/main/java/servlet/tck/signature/SignatureTestDriver.java
tck/tck-runtime/src/main/java/servlet/tck/signature/SignatureTestDriverFactory.java
tck/tck-runtime/src/main/resources/servlet/tck/signature/jakarta.servlet.sig_6.1
tck/tck-runtime/src/main/resources/servlet/tck/signature/sig-test-pkg-list.txt
tck/tck-runtime/src/main/resources/servlet/tck/signature/sig-test.map

Machinery copied from EL with some code clean up (warnings fixed, unused code removed, added generics).
Tested with Tomcat that has it's own Servlet API JAR and found a Tomcat bug that has since been fixed.

Add signature test to Servlet TCK

---

tck/tck-runtime/src/main/java/servlet/tck/api/jakarta_servlet_http/cookie/CookieTests.java
tck/tck-runtime/src/main/java/servlet/tck/api/jakarta_servlet_http/cookie/TestServlet.java
tck/tck-runtime/src/main/java/servlet/tck/pluggability/api/jakarta_servlet_http/cookie/CookieTests.java

This TCK update contains the following changes:
- code clean-up to remove all IDE warnings
- remove of tests explicitly testing RFC2109 syntax
- additional tests to check secure attribute via `[g|s]etSecure()` `[g|s]etAttribute()`
- new test for cookie values with quotes (RFC 6265 says the quotes are part of the value)
- version tests are more explicit that `setVersion()` is a NO-OP
- checks that server doesn't send `Max-Age=0`
- adds check that server sends `Expires` value in the past for `Max-Age=0`
- new tests for `HttpOnly`
The tests pass with the current Tomcat 11.0.x development branch although a few minor changes were required to achieve that.
These changes definitely need time for review but we are also up against the deadline for the release. I'll try and wait a full week before …

TCK updates - cookies

---

README.md
tck/README.md
tck/tck-runtime/src/main/java/servlet/tck/common/servlets/CommonServlets.java

We need to include slf4j librairies for remote managed container as it is not avaible as embeded container

---

api/src/main/resources/jakarta/servlet/resources/jakartaee_11.xsd
api/src/main/resources/jakarta/servlet/resources/jsp_4_0.xsd
api/src/main/resources/jakarta/servlet/resources/web-app_6_1.xsd
api/src/main/resources/jakarta/servlet/resources/web-common_6_1.xsd
api/src/main/resources/jakarta/servlet/resources/web-fragment_6_1.xsd
api/src/main/resources/jakarta/servlet/resources/web-jsptaglibrary_4_0.xsd

These should be the final versions but they weren't all available in the jakarta-schemas repository. I have provided PRs to jakarta-schemas and built the schemas required for the Servlet AOI locally. There is a (slim) chance that we'll need to update these again before the final release.
This should be uncontroversial as the 6.1 schemas are just the 6.0 schemas with a version update and one minor comment clarification. Given that and the looming deadline, I intend to merge immediately.

Add Jakarta EE 11 schema

---

api/src/test/java/ee/jakarta/servlet/MockServletConfig.java
api/src/test/java/ee/jakarta/servlet/MockServletContext.java
api/src/test/java/ee/jakarta/servlet/MockServletOutputStream.java
api/src/test/java/ee/jakarta/servlet/MockServletRequest.java
api/src/test/java/ee/jakarta/servlet/MockServletResponse.java
api/src/test/java/ee/jakarta/servlet/http/CanonicalUriPathTest.java
api/src/test/java/ee/jakarta/servlet/http/CookieTest.java
api/src/test/java/ee/jakarta/servlet/http/HttpServletTest.java
api/src/test/java/ee/jakarta/servlet/http/MockHttpServletRequest.java
api/src/test/java/ee/jakarta/servlet/http/MockHttpServletResponse.java

Fix #615. Only API code should be in the jakarta package

---

api/src/main/java/jakarta/servlet/http/Cookie.java

Given that we want a boolean, use the method that returns one.
Should be uncontroversial. I'll merge tomorrow unless there are objections.

Use method that returns boolean rather than Boolean

---

spec/src/main/asciidoc/servlet-spec-body.adoc

for #682
I'll backport this change to the 6.1 branch once it is merged into the main branch.
1) Adding the `jakarta.servlet.error.method` to the request attribute table. 
2) Organize the request attribute table

Add jakarta.servlet.error.method to Table 10-1 and organize

---

tck/tck-runtime/src/main/java/servlet/tck/spec/httpservletresponse/HttpServletResponseTests.java
tck/tck-runtime/src/main/java/servlet/tck/spec/httpservletresponse/HttpTestServlet.java

Replace the disputed test (that tests poorly defined behaviour of a bad servlet) with two tests that check the accepted behaviour of a well written servlet.
Once there is an accepted interpretation of the behaviour for the bad servlet, additional tests can be added to check that.

Fix #525 FlushBufferTest

---

README.md
spec/README.md

Given this branch is not regularly maintained I believe it's better to leave these parts out.
The (remaining) links to repo with more current README is enough.

Drop outdated sections

---

tck/tck-runtime/src/main/java/servlet/tck/pluggability/api/jakarta_servlet/registration/RegistrationTests.java

resolves #734 
I'm not sure how this would go into 6.1, but we'd need it there as well. 
I've tested this on WildFly and it passes:
```
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.116 s -- in servlet.tck.pluggability.api.jakarta_servlet.registration.RegistrationTests
16:12:02,709 INFO  [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0272: Suspending server
16:12:02,711 INFO  [org.jboss.as.ejb3] (management-handler-thread - 1) WFLYEJB0493: Jakarta Enterprise Beans subsystem suspension complete
16:12:02,712 INFO  [org.jboss.as.server] (Management Triggered Shutdown) WFLYSRV0241: Shutting down in response to management operation 'shutdown'
16:12:02,716 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-5) WFLYJCA0010: …
```

[734] Add the AddFilterString to the deployment.

---

tck/tck-docs/TCK-Exclude-List.txt
tck/tck-runtime/src/main/java/servlet/tck/spec/httpservletresponse/HttpServletResponseTests.java
tck/tck-runtime/src/main/java/servlet/tck/spec/httpservletresponse/HttpTestServlet.java

Revert #680 in 6.1.x.
Also `@Ignore` the challenged test.

Revert PR 680 and also Ignore the challenged test

---

spec/src/main/asciidoc/servlet-spec-body.adoc

Part of URI Path Canonicalization.

Clarify the description of when and how segments are re-encoded

---

api/src/main/java/jakarta/servlet/ServletContext.java

For Jakarta EE 12, the plan is to update all APIs to remove references to the SecurityManager and related APIs in preparation for Java SE 29 which may remove the API or not allow it to be run.  For servlet the only reference I saw was in Javadoc.
Fixes #789

Remove SecurityManager related code from API

---

api/src/main/java/jakarta/servlet/http/HttpServlet.java

Fixes the typo described in https://github.com/jakartaee/servlet/issues/815.

fixes typo in JavaDoc of HttpServlet.doPatch

---

spec/src/main/asciidoc/servlet-spec-body.adoc

This should be uncontroversial as it essentially documents the view of the Servlet EG since Servlet 3.0 times.

Fix #7 - clarify welcome files and filter mapping

---

spec/src/main/asciidoc/servlet-spec-body.adoc

Manually enabling the attributes substitution disabled the default specialchars substitution which needed to be explicitly re-enabled.

Fix #864 - re-enable specialchars substitution

---

spec/pom.xml

Just for consistency as using 1.8 causes:
```
[ERROR] org.apache.maven.plugin.PluginContainerException: Unable to load the mojo 'process-asciidoc' in the plugin 'org.asciidoctor:asciidoctor-maven-plugin:3.2.0' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/asciidoctor/maven/AsciidoctorMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
Which is hard to get anyway as after 52077a28 using 1.8 causes in first place:
```
Unrecognized option: --add-opens
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Update JDK required to build spec

---

tck/tck-runtime/src/main/java/servlet/tck/api/jakarta_servlet_http/sessioncookieconfig/TestServlet.java
tck/tck-runtime/src/main/java/servlet/tck/webxml/api/jakarta_servlet_http/sessioncookieconfig/SessionCookieConfigTests.java
tck/tck-runtime/src/main/java/servlet/tck/webxml/api/jakarta_servlet_http/sessioncookieconfig/TestListener.java
tck/tck-runtime/src/main/java/servlet/tck/webxml/api/jakarta_servlet_http/sessioncookieconfig/TestServlet.java
tck/tck-runtime/src/main/java/servlet/tck/webxml/api/jakarta_servlet_http/sessioncookieconfig/servlet_xjsh_sessioncookieconfig_web.xml

This fixes #681. 
It adds some new test cases for web.xml configuration of SessionCookieConfig based on the programmatic tests.
I've built the TCK locally and confirmed that the newly added tests pass when run with the latest Tomcat 12.0.x code.
I'm not expecting this to be controversial so I'm intending to merge this shortly.

Fix issue 681
