jakartaee/servlet

pom.xml
Signed-off-by: Guillermo González de Agüero <z06.guillermo@gmail.com>
=> Changed groupId and artifactId. Fixes #206 (EE4J)

pom.xml
Signed-off-by: Guillermo González de Agüero <z06.guillermo@gmail.com>
=> Changed groupId and artifactId. Fixes #206 (master)

pom.xml
=> Update to 1.0.2 of parent and simple cleanups

pom.xml
This plugin was adding the CCDL license to the final jar
Signed-off-by: Stuart Douglas <stuart.w.douglas@gmail.com>
=> Remove maven-remote-resources-plugin

pom.xml
Update to 1.0.2 of parent and simple cleanups
#	pom.xml
=> Align master with pom.xml changes in EE4J_8

pom.xml
=> Use nexus staging maven plugin

src/main/java/javax/servlet/ServletOutputStream.java
Make ServletOutputStream print methods compatible with async writing for #228
=> Issue #228 async print

.gitignore, api/pom.xml, pom.xml, spec/pom.xml
replaces #249
Signed-off-by: Greg Wilkins <gregw@webtide.com>
=> Update to version 4.0.3-SNAPSHOT

api/pom.xml, api/src/main/java/javax/servlet/ServletContext.java, api/src/main/java/javax/servlet/http/HttpSession.java, api/src/main/java/javax/servlet/package.html
Additional jakarta renaming changes for #243 
These may be too late for the actual release, but best to capture them for future releases.
Signed-off-by: Greg Wilkins <gregw@webtide.com>
=> EE8 Renaming for #243

api/pom.xml, api/src/main/javadoc/doc-files/speclicense.html
=> Add doc-files/speclicense.html

spec/src/main/asciidoc/license-efsl.adoc, spec/src/main/asciidoc/servlet-spec.adoc
=> Added Eclipse copyright, removed version from doctitle

api/pom.xml
=> Removed 2017-2019 copyright range and align javadoc with other specs

api/pom.xml
=> Merge final release branch 4.0.3

api/src/main/java/jakarta/servlet/http/HttpServlet.java
In the rename this class seems to have lost some imports,
so the build currently fails.
Signed-off-by: Stuart Douglas <stuart.w.douglas@gmail.com>
=> Fix build by adding missing imports

api/pom.xml, spec/pom.xml
Signed-off-by: Stuart Douglas <stuart.w.douglas@gmail.com>
=> Use 5.0 version

.github/workflows/maven.yml
This will test master and pull requests.
=> Add Github actions CI

api/pom.xml
jakarta-servlet-api.jar shall contain:
/ -
META-INF /
LICENSE.md
NOTICE.md
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>
=> Legal files fixed for multi module project structure

CONTRIBUTING.md
=> Issue #295 Contributing Guidelines

CONTRIBUTING.md
=> Add Eclipse Development Process info

api/src/main/java/javax/servlet/http/HttpServlet.java
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>
=> javax version of HTTP/2 fix for not supported methods

api/pom.xml, pom.xml, spec/pom.xml
* Tidy
* Update versions
* API pom directly uses EE4J parent
* Remove unneeded things
=> Clean poms and make more consistent with other projects

spec/src/main/asciidoc/servlet-spec-body.adoc
Signed-off-by: Thiago Henrique Hüpner <thihup@gmail.com>
=> Fix formatting

spec/src/main/asciidoc/scope.adoc, spec/src/main/asciidoc/servlet-spec-body.adoc, spec/src/main/asciidoc/servlet-spec.adoc
Reviewed references to Java, removed from old JCP/EG references, "JakartaEE" -> "Jakarta EE", version number updates.
=> Spec review part1

spec/src/main/asciidoc/servlet-spec-body.adoc
Signed-off-by: Thiago Henrique Hüpner <thihup@gmail.com>
=> Fix typo auth-contraint -> auth-constraint

api/src/main/java/jakarta/servlet/http/HttpServlet.java
=> Fix IDE warning. Remove unused throws declaration on private method

spec/src/main/asciidoc/servlet-spec-body.adoc
This is the first of what experience suggests will be several passes over the spec to review it. This PR addresses the remaining formatting issues in the automatic translation, clean-ups the cross-references and checks all the cross-references work.
=> Spec pass 1

spec/src/main/asciidoc/servlet-spec-body.adoc
Correct a few things in the previous pass and a couple of additional issues that have been identified.
=> Spec pass 4

api/pom.xml, spec/pom.xml
=> Update poms - automatic module and versions 

api/src/main/javadoc/doc-files/speclicense.html, spec/src/main/asciidoc/license-efsl.adoc
=> #317 - Update EFSL for Specifications and Javadoc

api/src/main/java/jakarta/servlet/ServletContext.java, spec/pom.xml
Also replaced one missing Java EE branding issue
Signed-off-by: Jean-Louis Monteiro <jlmonteiro@tomitribe.com>
=> Add jakarta prefix to generated file names (specs)

NOTICE.md
=> #347 - Update NOTICE to take Apache license into account

spec/src/main/asciidoc/license-efsl.adoc
=> Fix missing header causing warning

api/pom.xml, copyright-exclude
[javaee:README](https://github.com/javaee/servlet-spec/blob/d3d0f3ba4dc9256122f01ebdd4be4fae2a586df3/src/main/resources/META-INF/README#L41-L44) (since 2010)
I took that effort mentioned above already and instead of waiting for the original author to have some time in the future I present this change for consideration today.
I've built api module twice (from current master (20c4e41) and from 539c30b presented in this PR) and here is the diff of manifests from produced jars:
```
6c6
< Bnd-LastModified: 1599586342818
---
> Bnd-LastModified: 1599586039507
```
which I feel is acceptable.
=> Remove empty manifest and readme

api/pom.xml, pom.xml, spec/pom.xml
=> Merge from release branch

api/pom.xml, api/src/main/resources/jakarta/servlet/resources/web-app_5_1.xsd, api/src/main/resources/jakarta/servlet/resources/web-common_5_1.xsd, api/src/main/resources/jakarta/servlet/resources/web-fragment_5_1.xsd, pom.xml, spec/pom.xml, spec/src/main/asciidoc/license-efsl.adoc, spec/src/main/asciidoc/servlet-spec-body.adoc
=> Begin work on Servlet 5.1

spec/src/main/asciidoc/servlet-spec-body.adoc
Fixes #272
To avoid conflicts I have based it on my existing 5.1 PR. I have also included a link to the GH issue in the changelog, which I think could be useful for people to see the context/discussion around any changes.
=> Remove the X-Powered-By header 

api/src/main/java/jakarta/servlet/http/Cookie.java
=> Avoid NPE when passing null to Cookie#setDomain

api/src/main/java/jakarta/servlet/http/Part.java
Signed-off-by: Jerry Zhang <582315171@qq.com>
=> misspelling

api/src/main/java/jakarta/servlet/ServletContext.java
I think this correctly reflects the discussion. Happy to tweak as necessary.
=> Fix #105 - clarify requirements for path in getRealPath(String path)

api/src/main/java/jakarta/servlet/ServletResponse.java
=> Fix copy/paste error

api/src/main/java/jakarta/servlet/http/Cookie.java
=> Check system prop in doPrivileged block

api/src/main/java/jakarta/servlet/descriptor/JspPropertyGroupDescriptor.java
This is in support of:
https://github.com/eclipse-ee4j/jsp-api/issues/40
There will be related PRs to jakarta-schemas and jsp-api
=> Add support for an additional property: getErrorOnELNotFound()

api/pom.xml
=> Fixes generation of javadoc using JDK 11

api/src/main/java/jakarta/servlet/ServletInputStream.java, api/src/main/java/jakarta/servlet/ServletOutputStream.java
Make clear the scheduling implications of a false return from isReady()
=> Update javadoc for isReady

api/src/main/java/jakarta/servlet/MultipartConfigElement.java
Fix #463. Clarifications and Javadoc fixes. Nothing controversial.
=> Fix #463 - Javadoc fixes

api/pom.xml
Signed-off-by: Hervé Boutemy <hboutemy@apache.org>
=> Make API build reproducible

api/pom.xml, api/src/main/java/jakarta/servlet/http/HttpServletResponse.java
Trivial fixes so I intend to merge this immediately.
=> Fix copyright

spec/src/main/asciidoc/servlet-spec-body.adoc
This are not intended to hyperlinks
=> Fix asciidoctor build warnings

api/src/main/java/jakarta/servlet/ServletRequestWrapper.java, api/src/main/java/jakarta/servlet/http/HttpServlet.java, api/src/main/java/jakarta/servlet/http/HttpServletResponse.java, api/src/main/java/jakarta/servlet/http/HttpServletResponseWrapper.java
Trivial fix so I intend to apply with minimal delay.
=> Add missing @since tags

api/src/main/java/jakarta/servlet/http/HttpServlet.java
This should be uncontroversial. I'll leave it a few days for feedback and then merge if there are no objections.
=> Fix trace multiple headers

api/pom.xml, pom.xml, spec/pom.xml
Updating versions prior to generating M1.
=> Version update

spec/src/main/asciidoc/servlet-spec-body.adoc
=> Add request attribute for secure_protocol.

api/src/main/java/jakarta/servlet/ServletRequest.java
I missed a method in the original fix.
I don't think this is controversial. I plan to merge this early next unless there are objections.
=> Additional fix for #453

tck/tck-runtime/src/main/java/servlet/tck/spec/serverpush/ServerPushTests.java
Obvious typo. I intend to merge this immediately.
=> Fix typo in test class name

tck/tck-runtime/src/main/java/servlet/tck/api/jakarta_servlet_http/sessioncookieconfig/TestListener.java
I'll leave this at least 24 hours before merging
=> Fix pluggability test. Listener is shared. Don't hard-code context path.

spec/src/main/asciidoc/license-efsl.adoc, spec/src/main/asciidoc/servlet-spec-body.adoc
A handful of proof-reading fixes for the Servlet spec. I haven't done a thorough proof read this time (although I have in the past). These were the issues I spotting skimming through the PDF.
I'm about done for the day so I'll leave it until tomorrow to merge this so folks have a (small) chance to review since I don't need to merge it now.
I'm expecting to tag the 6.1.0 release shortly after merging this PR.
=> Proof reading

.github/dependabot.yml, .mvn/extensions.xml
=> Add dependabot configuration to propose some upgrade on dependencies and GH actions

api/src/main/resources/jakarta/servlet/resources/jakartaee_11.xsd
Found another issue in the schema repo.
=> Correct schema version

tck/tck-docs/userguide/pom.xml, tck/tck-runtime/pom.xml
=> fix the build as 6.1.0 is not available in Maven central

spec/pom.xml
This reverts commit 28a4bbecaabd282c51ed43c03b6c8833f727a299.
=> Revert Dependabot's JRuby update - it breaks the spec build

api/pom.xml, pom.xml, spec/pom.xml, tck/pom.xml, tck/tck-dist/pom.xml, tck/tck-docs/userguide/pom.xml, tck/tck-runtime/pom.xml, tck/tck-util/pom.xml
According to https://github.com/jakartaee/servlet/issues/651
=> Merge 6.1.0 release into master

tck/pom.xml, tck/tck-dist/pom.xml, tck/tck-runtime/pom.xml
=> as TCK modules does not inherit servlet module, we need to setup some Maven plugins/configuration

tck/pom.xml, tck/tck-dist/pom.xml, tck/tck-runtime/pom.xml
right better target master first 
cherry-pick of https://github.com/jakartaee/servlet/pull/676
=> as TCK modules does not inherit servlet module, we need to setup some Maven plugins/configuration (#676) (cherry-pick from 6.1.x)

spec/src/main/asciidoc/servlet-spec-body.adoc
for https://github.com/jakartaee/servlet/issues/682
Changes already merged to master: https://github.com/jakartaee/servlet/pull/683
1.  Adding the jakarta.servlet.error.method to the request attribute table.
2. Organize the request attribute table
=> Add jakarta.servlet.error.method to Table 10-1 and organize

tck/tck-runtime/src/main/java/servlet/tck/api/jakarta_servlet_http/cookie/CookieTests.java, tck/tck-runtime/src/main/java/servlet/tck/api/jakarta_servlet_http/cookie/TestServlet.java, tck/tck-runtime/src/main/java/servlet/tck/pluggability/api/jakarta_servlet_http/cookie/CookieTests.java, tck/tck-runtime/src/main/java/servlet/tck/spec/defaultmapping/DefaultMappingTests.java, tck/tck-runtime/src/main/resources/servlet/tck/signature/sig-test.map
A collection of small TCK fixes and updates. Shouldn't be anything controversial.
=> Tck fixes 6.1.x

.github/dependabot.yml
=> add dependabot for branch 6.1.x

api/src/main/java/jakarta/servlet/http/Cookie.java, api/src/main/java/jakarta/servlet/http/PushBuilder.java, spec/src/main/asciidoc/servlet-spec-body.adoc, tck/tck-runtime/src/main/java/servlet/tck/spec/serverpush/ServerPushTests.java, tck/tck-runtime/src/main/java/servlet/tck/spec/serverpush/TestServlet4.java
I plan to leave this open for at least 72 hours for comments/reviews before merging.
=> Fix issue 661

api/pom.xml
=> Simplify dependencies by using bom, and fix dependency to junit api

api/pom.xml
=> Simplify dependencies by using bom, and fix dependency to junit api (#852)

api/src/main/java/jakarta/servlet/ServletContext.java, spec/src/main/asciidoc/servlet-spec-body.adoc
Clarification based on wording suggested by @gregw.
I'll leave this open for a week or so for comment before (assuming no objections) adding some additional TCK tests and merging.
=> Fix #11 - clarify behaviour of ServletContext.getRealPath()

api/src/main/java/jakarta/servlet/http/HttpServletRequest.java, spec/src/main/asciidoc/servlet-spec-body.adoc
I plan to leave this open for at least a week for feedback before merging (assuming there are no objections).
=> Fix #18 - clarify behaviour of HttpServletRequest.getContextPath()

api/src/main/java/jakarta/servlet/http/HttpServletRequest.java, spec/src/main/asciidoc/servlet-spec-body.adoc
Should be uncontroversial.
I'll leave this open for a couple of days for feedback on the wording and, assuming no objections, merge it.
=> Fix issue #859

api/src/main/java/jakarta/servlet/http/HttpServlet.java, spec/src/main/asciidoc/servlet-spec-body.adoc
=> Fix #867 - ignore invalid If-Modified-Since headers
